apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: "10.21.14.21.xip.io"
      http:
        paths:
          - backend:
              serviceName: jenkins
              servicePort: 8080
            path: /
